name: Hanode Add-on
version: "1.0.6"
slug: hanode
description: Write automations in Typescript and RxJS
url: "https://github.com/hanodeorg/hanode-addon"
image: "ghcr.io/hanodeorg/image-{arch}-hanode-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  home_assistant_url: "http://10.0.4.10:8123"
  home_assistant_access_token: "???"
  script_for_errors: ""
schema:
  home_assistant_url: "str"
  home_assistant_access_token: "password"
  script_for_errors: "str?"
